# Generated by Django 3.1.3 on 2021-01-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type_name', models.CharField(max_length=255, verbose_name='Course Type')),
            ],
        ),
    ]
