# Generated by Django 3.1.3 on 2021-01-31 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanel_name', models.CharField(max_length=255, verbose_name='Channel name')),
                ('channel_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('channel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course_type')),
            ],
        ),
    ]
