# Generated by Django 3.1.3 on 2021-01-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_channel_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel_details',
            name='chanel_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Channel name'),
        ),
    ]
