# Generated by Django 3.1.3 on 2021-02-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210131_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_lecture',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_video', models.CharField(max_length=255, verbose_name='Video Title')),
                ('uploaded_on', models.DateField(auto_now_add=True, verbose_name='Uploaded On')),
                ('details', models.TextField(max_length=500, verbose_name='Details')),
            ],
        ),
    ]
