# Generated by Django 3.1.3 on 2021-02-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_lecture_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_lecture',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_lectures', verbose_name='Video'),
        ),
    ]
