# Generated by Django 3.1.3 on 2021-02-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_video_lecture_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_details',
            name='channel_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
