# Generated by Django 3.1.3 on 2021-02-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_channel_details_channel_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel_details',
            old_name='chanel_name',
            new_name='channel_name',
        ),
        migrations.AlterField(
            model_name='channel_details',
            name='channel_logo',
            field=models.ImageField(blank=True, null=True, upload_to='channel_logo'),
        ),
    ]
