# Generated by Django 3.1.3 on 2021-02-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20210211_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities_course',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Duration of Course(in days)'),
        ),
        migrations.AlterField(
            model_name='universities_course',
            name='course_offered',
            field=models.CharField(max_length=250, verbose_name='Course Name'),
        ),
    ]
