# Generated by Django 3.1.3 on 2021-02-18 15:01

from django.db import migrations, models
import django.db.models.deletion
import universities.models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_auto_20210216_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecutures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.FileField(blank=True, null=True, upload_to=universities.models.set_lecture_url)),
                ('university_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.universities_course')),
            ],
        ),
    ]
