# Generated by Django 3.1.3 on 2021-02-20 14:37

from django.db import migrations, models
import universities.models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_lecutures'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecutures',
            name='tumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=universities.models.set_lecture_thumdnail_url),
        ),
    ]
