# Generated by Django 3.1.3 on 2021-02-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_lecutures_tumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecutures',
            old_name='tumbnail',
            new_name='thumbnail',
        ),
    ]
